apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  labels:
    app: elasticsearch
    component: kibana
data:
  kibana.yml: |
    ---
    server.name: kibana
    server.host: "0"
    elasticsearch.url: http://es-http:9200
