apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  selector:
    matchLabels:
      component: elasticsearch
      role: data
  serviceName: elasticsearch-data
  replicas: 3
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      containers:
      - name: es-data
        image: raaftech/elasticsearch:6.4.3
        env:
        - name: ES_ALLOW_MMAPFS
          value: "false"
        - name: ES_CLUSTER_NAME
          value: "es-cluster"
        - name: ES_DISCOVERY_SERVICE
          value: "elasticsearch-discovery"
        - name: ES_INDEX_STORE_TYPE
          value: "niofs"
        - name: ES_JAVA_OPTS
          value: "-Des.scripting.exception_for_missing_value=true -Xms1g -Xmx1g"
        - name: ES_NODE_DATA
          value: "true"
        - name: ES_NODE_INGEST
          value: "false"
        - name: ES_NODE_MASTER
          value: "false"
        - name: ES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          requests:
            cpu: 0.25
          limits:
            cpu: 1
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
        - name: storage
          mountPath: /elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      storageClassName: glusterfs-storage
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 12Gi
