apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-master
  labels:
    component: elasticsearch
spec:
  selector:
    matchLabels:
      component: elasticsearch
      role: master
  serviceName: es-transport
  replicas: 3
  template:
    metadata:
      labels:
        component: elasticsearch
        http: disabled
        role: master
    spec:
      containers:
      - name: es-master
        image: raaftech/elasticsearch:latest
        imagePullPolicy: Always
        env:
        - name: ES_ALLOW_MMAPFS
          value: "false"
        - name: ES_CLUSTER_NAME
          value: "es-cluster"
        - name: ES_DISCOVERY_SERVICE
          value: "es-transport"
        - name: ES_INDEX_STORE_TYPE
          value: "niofs"
        - name: ES_NODE_DATA
          value: "false"
        - name: ES_NODE_INGEST
          value: "false"
        - name: ES_NODE_MASTER
          value: "true"
        - name: ES_NUMBER_OF_MASTERS
          value: "2"
        - name: ES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          requests:
            cpu: 0.25
            memory: 4Gi
          limits:
            cpu: 1
            memory: 4Gi
        ports:
        - containerPort: 9300
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: storage
          mountPath: /elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      storageClassName: glusterfs-storage-block
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 10Gi
